algorithm: 
  name: SAC_REG
  tau: 0.005
  gamma: 0.99
  alpha: 1
  policy: Gaussian
  target_update_interval: 1
  automatic_entropy_tuning: True
  device: cuda:0
  hidden_size: 256
  lr: 0.0003
  target_entropy: null
  action_penalty: 0