name: cartpole-v0
m1: 0.1
m2: 0.1
l: 0.3
fp: 0.01
fr: 0.01
g: 9.81
x_lim: 1
theta_lim: 3.15
xdot_lim: 20
thetadot_lim: 100
survival_reward: 55
x_penalty: 5
theta_penalty: 5
xdot_penalty: 0
thetadot_penalty: 0
f_lim: 10
tau_lim: 10
f_penalty: 1
tau_penalty: 1
delta_t: 0.01
t_max: 30
f_residual_scale: 0.1
tau_residual_scale: 0.1
f_residual_lim: 1
tau_residual_lim: 1