name: cartpole-v0
m1: 1.0
m2: 1.0
l: 1.0
fp: 0.1
fr: 0.1
g: 9.81
x_lim: 1
theta_lim: 10000
xdot_lim: 10000
thetadot_lim: 10000
survival_reward: 0
x_penalty: 5
theta_penalty: 5
xdot_penalty: 1
thetadot_penalty: 1
f_lim: 10
tau_lim: 9
f_penalty: 1
tau_penalty: 1
delta_t: 0.01
t_max: 1000
f_residual_scale: 0.1
tau_residual_scale: 0.1
f_residual_lim: 1
tau_residual_lim: 1