defaults:
  - sim_config: cartpole-v0
  - train_config: SAC
  - _self_

train_config:
  log_dir: /logs/
  total_train_steps: 1000000
  eval_freq: 5000
  n_eval_episodes: 1
  batch_size: 256
  seed: 0
  replay_size: 100000
  updates_per_step: 1
  start_steps: 1000
  eval: True
  no_improve_lim: 100000
  env_switch_freq: 2000000