defaults:
  - sim_config: cartpole-v1
  - train_config: SAC
  - _self_

train_config:
  log_dir: logs/
  total_train_steps: 300000
  eval_freq: 5000
  batch_size: 256
  seed: 0
  replay_size: 100000
  updates_per_step: 1
  start_steps: 0

run_config:
  run_identifier: Under_Act_Cartpole_Agent2